export const napcatChannelConfigSchema = {
    type: "object",
    properties: {
        url: { type: "string", title: "NapCat HTTP URL", default: "http://127.0.0.1:3000" },
        transport: {
            type: "string",
            title: "Transport",
            description: "Transport mode: http, ws-client, ws-server",
            default: "http",
            enum: ["http", "ws-client", "ws-server"],
        },
        wsUrl: {
            type: "string",
            title: "NapCat WebSocket URL (client mode)",
            description: "Used when transport=ws-client, e.g. ws://127.0.0.1:3001",
            default: "",
        },
        wsHost: {
            type: "string",
            title: "WebSocket Host",
            description: "Server bind host for ws-server mode, or fallback host for ws-client when wsUrl is empty",
            default: "0.0.0.0",
        },
        wsPort: {
            type: "number",
            title: "WebSocket Port",
            description: "Server bind port for ws-server mode, or fallback port for ws-client",
            default: 3001,
        },
        wsPath: {
            type: "string",
            title: "WebSocket Path",
            description: "WebSocket path, e.g. /onebot/v11/ws",
            default: "/",
        },
        wsToken: {
            type: "string",
            title: "WebSocket Token",
            description: "Optional WS token (Authorization Bearer + access_token query)",
            default: "",
        },
        wsHeartbeatMs: {
            type: "number",
            title: "WebSocket Heartbeat Interval (ms)",
            description: "Heartbeat interval in milliseconds",
            default: 30000,
        },
        wsReconnectMs: {
            type: "number",
            title: "WebSocket Reconnect Interval (ms)",
            description: "Reconnect interval for ws-client mode in milliseconds",
            default: 30000,
        },
        wsRequestTimeoutMs: {
            type: "number",
            title: "WebSocket Request Timeout (ms)",
            description: "Timeout waiting action response in WS modes",
            default: 10000,
        },
        inboundImageEnabled: {
            type: "boolean",
            title: "Enable Inbound Image Parsing",
            description: "When enabled, parse CQ:image/CQ:record from inbound messages into media fields",
            default: true,
        },
        inboundImagePreferUrl: {
            type: "boolean",
            title: "Prefer CQ URL For Inbound Images",
            description: "When true, prefer CQ url field over file id when building inbound image URLs",
            default: true,
        },
        inboundMediaDir: {
            type: "string",
            title: "Inbound Media Cache Directory",
            description: "Directory used to cache inbound media files locally before passing to OpenClaw",
            default: "./workspace/napcat-inbound-media",
        },
        inboundMediaAutoCleanupEnabled: {
            type: "boolean",
            title: "Enable Inbound Media Auto Cleanup",
            description: "Automatically sweep expired inbound media files from the local cache directory",
            default: true,
        },
        inboundMediaTtlMs: {
            type: "number",
            title: "Inbound Media TTL (ms)",
            description: "How long inbound media files and context IDs stay reusable before expiring",
            default: 86400000,
        },
        inboundMediaCleanupMinIntervalMs: {
            type: "number",
            title: "Inbound Media Cleanup Min Interval (ms)",
            description: "Minimum delay between inbound media cache sweeps to avoid scanning on every message",
            default: 300000,
        },
        streamTempAutoCleanupEnabled: {
            type: "boolean",
            title: "Enable Stream Temp Auto Cleanup",
            description: "Automatically clean NapCat stream temp files after successful stream actions when safe",
            default: true,
        },
        streamTempAutoCleanupMode: {
            type: "string",
            title: "Stream Temp Auto Cleanup Mode",
            description: "Use safe mode to clean NapCat stream temp files only when no stream actions are still running",
            default: "safe",
            enum: ["off", "safe"],
        },
        agentId: {
            type: "string",
            title: "Fixed Agent ID",
            description: "Optional: force all NapCat inbound sessions to use this OpenClaw agent ID",
            default: "",
        },
        allowUsers: {
            type: "array",
            items: { type: "string" },
            title: "Allowed User IDs",
            description: "Only accept messages from these QQ user IDs (empty = accept all)",
            default: [],
        },
        token: {
            type: "string",
            title: "NapCat Access Token",
            description: "Optional NapCat HTTP API token (sent as Authorization Bearer and access_token query)",
            default: "",
        },
        enableGroupMessages: {
            type: "boolean",
            title: "Enable Group Messages",
            description: "When enabled, process group messages (requires mention to trigger)",
            default: false,
        },
        groupMentionOnly: {
            type: "boolean",
            title: "Require Mention in Group",
            description: "In group chats, only respond when the bot is mentioned (@)",
            default: true,
        },
        mediaProxyEnabled: {
            type: "boolean",
            title: "Enable Media Proxy",
            description: "Expose /napcat/media endpoint so NapCat can fetch media from OpenClaw host",
            default: false,
        },
        publicBaseUrl: {
            type: "string",
            title: "OpenClaw Public Base URL",
            description: "Base URL reachable by NapCat device, e.g. http://192.168.1.10:18789",
            default: "",
        },
        mediaProxyToken: {
            type: "string",
            title: "Media Proxy Token",
            description: "Optional token required by /napcat/media endpoint",
            default: "",
        },
        voiceBasePath: {
            type: "string",
            title: "Voice Base Path",
            description: "Base directory for relative audio files (e.g. /tmp/napcat-voice)",
            default: "",
        },
        enableInboundLogging: {
            type: "boolean",
            title: "Enable Inbound Message Logging",
            description: "Log all received QQ/group messages before allowlist filtering",
            default: true,
        },
        inboundLogDir: {
            type: "string",
            title: "Inbound Log Directory",
            description: "Directory to store per-user/per-group inbound logs and notice audit logs",
            default: "./logs/napcat-inbound",
        },
        actionTimeoutMs: {
            type: "number",
            title: "Action Timeout (ms)",
            description: "Optional generic NapCat action timeout hint for future extensions; WS calls still use wsRequestTimeoutMs",
            default: 10000,
        },
        autoApproveFriendRequests: {
            type: "boolean",
            title: "Auto Approve Friend Requests",
            description: "Automatically approve inbound friend requests",
            default: false,
        },
        friendAutoRemarkTemplate: {
            type: "string",
            title: "Friend Auto Remark Template",
            description: "Optional template used when auto-approving friend requests. Supports {userId}, {nickname}, {comment}",
            default: "",
        },
        friendRequestAllowUsers: {
            type: "array",
            items: { type: "string" },
            title: "Friend Request Allowed User IDs",
            description: "Only auto-approve friend requests from these QQ user IDs (empty = allow all)",
            default: [],
        },
        friendRequestLogDir: {
            type: "string",
            title: "Friend Request Log Directory",
            description: "Directory to store friend/group request logs and action audit logs",
            default: "./logs/napcat-friend-requests",
        },
    },
};
